### ISSUE TITLE
[guide] GCE preemptive instance deployment

### ISSUE THREAD

**Issue by arunoda** [fastai/course-v3#16] opened 2018-10-22 14:42 UTC
This weekend, I just spend some time with GCE and trying to make some great fastai dev environment. 
That's with preemptive instances.

This is a set of scripts which I tested many times for different cases.
May be this is useful for others [setup a powerful fast.ai node](https://arunoda.me/blog/ideal-way-to-creare-a-fastai-node) for a very low price.

Guide: https://arunoda.me/blog/ideal-way-to-creare-a-fastai-node

Some features of this:

  * create a node with the **Tesla v100** GPU for just **$0.8/hour**
  * create a node with the **Tesla K80** GPU for just **$0.2/hour**
  * create a node with No GPU for just **$0.01/hour**
  * switch between these nodes whenever needed
  * install new tools and save data (won't get deleted when switching)
  * run notebooks by just starting the server (no SSH needed)
  * create a password protected jupyter notebooks environment

**Comment by discdiver** [comment] 2018-10-23 12:58
I can confirm those GPU prices.

@arunoda nice to see you here - I used to use your tools in Meteor-land. Looking forward to seeing what great things you create!

**Comment by jph00** [comment] 2018-10-23 20:28
Thanks for the post! Would be great if you could update your guide to take advantage of the fastai/pytorch instances. https://blog.kovalevskyi.com/google-compute-engine-now-has-images-with-pytorch-1-0-0-and-fastai-1-0-2-57c49efd74bb

I'll close this issue since this discussion is best had on the forum.

**Closed by jph00** 2018-10-23 20:28 UTC
